from app import app, db, WordPair
import json

# Convert the JavaScript word pairs to a Python list of dictionaries
word_pairs_js = """
[
    { "german": "das Fahrrad (die Fahrräder)", "correct": "bicycle", "incorrect": ["fork", "book", "car"] },
    { "german": "der Löffel (die Löffel)", "correct": "spoon", "incorrect": ["chair", "clock", "picture"] },
    { "german": "der Baum (die Bäume)", "correct": "tree", "incorrect": ["apple", "cup", "table"] },
    { "german": "die Tasse (die Tassen)", "correct": "cup", "incorrect": ["spoon", "clock", "house"] },
    { "german": "die Gabel (die Gabeln)", "correct": "fork", "incorrect": ["book", "cup", "tree"] },
    { "german": "der Hund (die Hunde)", "correct": "dog", "incorrect": ["apple", "book", "cup"] },
    { "german": "die Katze (die Katzen)", "correct": "cat", "incorrect": ["flower", "window", "shoe"] },
    { "german": "das Buch (die Bücher)", "correct": "book", "incorrect": ["bicycle", "cat", "door"] },
    { "german": "das Haus (die Häuser)", "correct": "house", "incorrect": ["tree", "fork", "cup"] },
    { "german": "der Schmetterling (die Schmetterlinge)", "correct": "butterfly", "incorrect": ["whale", "eagle", "shark"] },
    { "german": "das Fernglas (die Ferngläser)", "correct": "binoculars", "incorrect": ["telescope", "microscope", "camera"] },
    { "german": "die Kerze (die Kerzen)", "correct": "candle", "incorrect": ["lamp", "light", "lantern"] },
    { "german": "der Dünger (die Dünger)", "correct": "fertilizer", "incorrect": ["pesticide", "compost", "herbicide"] },
    { "german": "die Gondel (die Gondeln)", "correct": "gondola", "incorrect": ["yacht", "canoe", "raft"] },
    { "german": "das Gewürz (die Gewürze)", "correct": "spice", "incorrect": ["herb", "flavor", "seasoning"] },
    { "german": "die Mandel (die Mandeln)", "correct": "almond", "incorrect": ["peanut", "walnut", "cashew"] },
    { "german": "der Anker (die Anker)", "correct": "anchor", "incorrect": ["rudder", "sail", "hull"] },
    { "german": "die Flöte (die Flöten)", "correct": "flute", "incorrect": ["violin", "guitar", "drum"] },
    { "german": "der Gletscher (die Gletscher)", "correct": "glacier", "incorrect": ["volcano", "canyon", "waterfall"] },
    { "german": "das Gewitter (die Gewitter)", "correct": "thunderstorm", "incorrect": ["hurricane", "tornado", "blizzard"] },
    { "german": "der Leuchtturm (die Leuchttürme)", "correct": "lighthouse", "incorrect": ["windmill", "barn", "observatory"] },
    { "german": "das Labyrinth (die Labyrinthe)", "correct": "labyrinth", "incorrect": ["maze", "jungle", "forest"] },
    { "german": "die Sage (die Sagen)", "correct": "legend", "incorrect": ["fairy tale", "novel", "poem"] },
    { "german": "die Schublade (die Schubladen)", "correct": "drawer", "incorrect": ["shelf", "closet", "cupboard"] },
    { "german": "der Stachel (die Stacheln)", "correct": "spike", "incorrect": ["blade", "arrow", "hook"] },
    { "german": "das Teleskop (die Teleskope)", "correct": "telescope", "incorrect": ["microscope", "periscope", "binoculars"] },
    { "german": "die Waage (die Waagen)", "correct": "scale", "incorrect": ["meter", "ruler", "caliper"] },
    { "german": "der Wirbelsturm (die Wirbelstürme)", "correct": "cyclone", "incorrect": ["earthquake", "avalanche", "flood"] },
    { "german": "die Beere (die Beeren)", "correct": "berry", "incorrect": ["cherry", "nut", "peach"] },
    { "german": "das Fernrohr (die Fernrohre)", "correct": "telescope", "incorrect": ["microscope", "binoculars", "periscope"] },
    { "german": "der Giebel (die Giebel)", "correct": "gable", "incorrect": ["tower", "dome", "arch"] },
    { "german": "die Heide (die Heiden)", "correct": "heath", "incorrect": ["forest", "meadow", "swamp"] },
    { "german": "das Juwel (die Juwelen)", "correct": "jewel", "incorrect": ["gemstone", "crystal", "bead"] },
    { "german": "die Kluft (die Klüfte)", "correct": "gorge", "incorrect": ["valley", "plain", "hill"] },
    { "german": "der Lorbeer (die Lorbeeren)", "correct": "laurel", "incorrect": ["ivy", "cypress", "rosemary"] },
    { "german": "die Nelke (die Nelken)", "correct": "carnation", "incorrect": ["rose", "tulip", "lily"] },
    { "german": "das Panorama (die Panoramen)", "correct": "panorama", "incorrect": ["landscape", "portrait", "sketch"] },
    { "german": "die Pergola (die Pergolen)", "correct": "pergola", "incorrect": ["veranda", "gazebo", "balcony"] },
    { "german": "der Quader (die Quader)", "correct": "block", "incorrect": ["sphere", "cylinder", "cone"] },
    { "german": "die Rüstung (die Rüstungen)", "correct": "armor", "incorrect": ["weapon", "shield", "helm"] },
    { "german": "der Sattel (die Sättel)", "correct": "saddle", "incorrect": ["reins", "stirrup", "harness"] },
    { "german": "die Tarnung (die Tarnungen)", "correct": "camouflage", "incorrect": ["costume", "disguise", "uniform"] },
    { "german": "das Ultraschall (die Ultraschalle)", "correct": "ultrasound", "incorrect": ["X-ray", "MRI", "radiation"] },
    { "german": "die Welle (die Wellen)", "correct": "wave", "incorrect": ["tide", "whirlpool", "current"] },
    { "german": "das Zifferblatt (die Zifferblätter)", "correct": "dial", "incorrect": ["button", "switch", "lever"] },
    { "german": "der Abgrund (die Abgründe)", "correct": "abyss", "incorrect": ["valley", "peak", "cave"] },
    { "german": "die Brise (die Brisen)", "correct": "breeze", "incorrect": ["storm", "drizzle", "blizzard"] },
    { "german": "das Cello (die Celli)", "correct": "cello", "incorrect": ["violin", "harp", "piano"] },
    { "german": "der Dolch (die Dolche)", "correct": "dagger", "incorrect": ["sword", "spear", "axe"] },
    { "german": "die Juwelier (die Juweliere)", "correct": "jeweler", "incorrect": ["blacksmith", "carpenter", "tailor"] },
    { "german": "der Kosmos (die Kosmen)", "correct": "cosmos", "incorrect": ["universe", "galaxy", "nebula"] },
    { "german": "die Notiz (die Notizen)", "correct": "note", "incorrect": ["letter", "memo", "report"] },
    { "german": "das Paradoxon (die Paradoxa)", "correct": "paradox", "incorrect": ["dilemma", "mystery", "puzzle"] },
    { "german": "die Ananas (die Ananas)", "correct": "pineapple", "incorrect": ["apple", "pear", "peach"] },
    { "german": "die Dämmerung (die Dämmerungen)", "correct": "dusk", "incorrect": ["dawn", "midday", "midnight"] },
    { "german": "das Echo (die Echos)", "correct": "echo", "incorrect": ["sound", "noise", "whisper"] },
    { "german": "die Feder (die Federn)", "correct": "feather", "incorrect": ["scale", "fur", "shell"] },
    { "german": "das Gewürz (die Gewürze)", "correct": "spice", "incorrect": ["herb", "salt", "sugar"] },
    { "german": "der Hügel (die Hügel)", "correct": "hill", "incorrect": ["mountain", "valley", "plain"] },
    { "german": "die Insel (die Inseln)", "correct": "island", "incorrect": ["peninsula", "continent", "bay"] },
    { "german": "das Jubiläum (die Jubiläen)", "correct": "anniversary", "incorrect": ["celebration", "party", "festival"] },
    { "german": "der Käfig (die Käfige)", "correct": "cage", "incorrect": ["nest", "den", "hive"] },
    { "german": "die Lücke (die Lücken)", "correct": "gap", "incorrect": ["edge", "corner", "surface"] },
    { "german": "das Märchen (die Märchen)", "correct": "fairy tale", "incorrect": ["novel", "poem", "legend"] },
    { "german": "die Nadel (die Nadeln)", "correct": "needle", "incorrect": ["pin", "hook", "screw"] },
    { "german": "das Öl (die Öle)", "correct": "oil", "incorrect": ["vinegar", "sauce", "water"] },
    { "german": "die Pfote (die Pfoten)", "correct": "paw", "incorrect": ["hoof", "claw", "wing"] },
    { "german": "der Quark (die Quarks)", "correct": "curd", "incorrect": ["cheese", "yogurt", "butter"] },
    { "german": "die Ruine (die Ruinen)", "correct": "ruin", "incorrect": ["castle", "palace", "temple"] },
    { "german": "die Schaufel (die Schaufeln)", "correct": "shovel", "incorrect": ["rake", "hoe", "spade"] },
    { "german": "das Tal (die Täler)", "correct": "valley", "incorrect": ["hill", "mountain", "plateau"] },
    { "german": "die Wüste (die Wüsten)", "correct": "desert", "incorrect": ["forest", "jungle", "tundra"] },
    { "german": "backen (gebacken)", "correct": "bake", "incorrect": ["cook", "boil", "fry"] },
    { "german": "bauen (gebaut)", "correct": "build", "incorrect": ["destroy", "paint", "buy"] },
    { "german": "beissen (gebissen)", "correct": "bite", "incorrect": ["chew", "lick", "swallow"] },
    { "german": "brennen (gebrannt)", "correct": "burn", "incorrect": ["freeze", "melt", "boil"] },
    { "german": "empfehlen (empfohlen)", "correct": "recommend", "incorrect": ["order", "demand", "forbid"] },
    { "german": "fliegen (geflogen)", "correct": "fly", "incorrect": ["jump", "run", "swim"] },
    { "german": "gießen (gegossen)", "correct": "water", "incorrect": ["plant", "harvest", "prune"] },
    { "german": "graben (gegraben)", "correct": "dig", "incorrect": ["bury", "build", "plant"] },
    { "german": "klettern (geklettert)", "correct": "climb", "incorrect": ["fall", "slide", "jump"] },
    { "german": "kriechen (gekrochen)", "correct": "crawl", "incorrect": ["walk", "run", "hop"] },
    { "german": "leihen (geliehen)", "correct": "lend", "incorrect": ["borrow", "buy", "sell"] },
    { "german": "malen (gemalt)", "correct": "paint", "incorrect": ["draw", "sketch", "carve"] },
    { "german": "pfeifen (gepfiffen)", "correct": "whistle", "incorrect": ["sing", "shout", "hum"] },
    { "german": "raten (geraten)", "correct": "guess", "incorrect": ["know", "think", "understand"] },
    { "german": "reiten (geritten)", "correct": "ride", "incorrect": ["walk", "run", "drive"] },
    { "german": "schmelzen (geschmolzen)", "correct": "melt", "incorrect": ["freeze", "boil", "evaporate"] },
    { "german": "schwimmen (geschwommen)", "correct": "swim", "incorrect": ["dive", "float", "sink"] },
    { "german": "spinnen (gesponnen)", "correct": "spin", "incorrect": ["weave", "knit", "sew"] },
    { "german": "streichen (gestrichen)", "correct": "strike", "incorrect": ["cut", "carve", "build"] },
    { "german": "weben (gewebt)", "correct": "weave", "incorrect": ["knit", "sew", "stitch"] },
    { "german": "angeln (geangelt)", "correct": "fish", "incorrect": ["hunt", "sail", "dive"] },
    { "german": "atmen (geatmet)", "correct": "breathe", "incorrect": ["cough", "snore", "yawn"] },
    { "german": "blühen (geblüht)", "correct": "bloom", "incorrect": ["fade", "wilt", "grow"] },
    { "german": "ernten (geerntet)", "correct": "harvest", "incorrect": ["plant", "water", "plow"] },
    { "german": "falten (gefaltet)", "correct": "fold", "incorrect": ["cut", "tear", "glue"] },
    { "german": "harken (geharkt)", "correct": "rake", "incorrect": ["dig", "mow", "plant"] },
    { "german": "heilen (geheilt)", "correct": "heal", "incorrect": ["hurt", "break", "injure"] },
    { "german": "jagen (gejagt)", "correct": "hunt", "incorrect": ["fish", "trap", "tame"] },
    { "german": "kauen (gekaut)", "correct": "chew", "incorrect": ["bite", "lick", "suck"] },
    { "german": "kreisen (gekreist)", "correct": "circle", "incorrect": ["cross", "follow", "trace"] },
    { "german": "lächeln (gelächelt)", "correct": "smile", "incorrect": ["frown", "laugh", "grimace"] },
    { "german": "mischen (gemischt)", "correct": "mix", "incorrect": ["separate", "arrange", "align"] },
    { "german": "nähen (genäht)", "correct": "sew", "incorrect": ["knit", "weave", "stitch"] },
    { "german": "pflanzen (gepflanzt)", "correct": "plant", "incorrect": ["harvest", "water", "prune"] },
    { "german": "säen (gesät)", "correct": "sow", "incorrect": ["reap", "harvest", "water"] },
    { "german": "sammeln (gesammelt)", "correct": "collect", "incorrect": ["scatter", "discard", "ignore"] },
    { "german": "tauchen (getaucht)", "correct": "dive", "incorrect": ["swim", "float", "surf"] },
    { "german": "trocknen (getrocknet)", "correct": "dry", "incorrect": ["wet", "soak", "dampen"] },
    { "german": "verbinden (verbunden)", "correct": "connect", "incorrect": ["disconnect", "break", "separate"] },
    { "german": "wischen (gewischt)", "correct": "wipe", "incorrect": ["wash", "scrub", "rinse"] },
    { "german": "zählen (gezählt)", "correct": "count", "incorrect": ["measure", "weigh", "estimate"] },
    { "german": "ziehen (gezogen)", "correct": "pull", "incorrect": ["push", "lift", "carry"] },
    { "german": "zuhören (zugehört)", "correct": "listen", "incorrect": ["speak", "shout", "whisper"] },
    { "german": "brauen (gebraut)", "correct": "brew", "incorrect": ["bake", "stew", "fry"] },
    { "german": "dämpfen (gedämpft)", "correct": "steam", "incorrect": ["boil", "grill", "fry"] },
    { "german": "schweben (geschwebt)", "correct": "hover", "incorrect": ["sink", "dive", "float"] },
    { "german": "streuen (gestreut)", "correct": "scatter", "incorrect": ["collect", "gather", "pile"] },
    { "german": "kriechen (gekrochen)", "correct": "crawl", "incorrect": ["jump", "slide", "run"] },
    { "german": "lügen (gelogen)", "correct": "lie", "incorrect": ["truth", "confess", "promise"] },
    { "german": "schneiden (geschnitten)", "correct": "cut", "incorrect": ["tie", "break", "bind"] },
    { "german": "schwören (geschworen)", "correct": "swear", "incorrect": ["whisper", "shout", "speak"] },
    { "german": "spülen (gespült)", "correct": "rinse", "incorrect": ["soak", "dry", "fill"] },
    { "german": "der Anwalt (die Anwälte)", "correct": "lawyer", "incorrect": ["doctor", "engineer", "architect"] },
    { "german": "die Eule (die Eulen)", "correct": "owl", "incorrect": ["eagle", "sparrow", "dove"] },
    { "german": "das Gewächshaus (die Gewächshäuser)", "correct": "greenhouse", "incorrect": ["warehouse", "lighthouse", "barn"] },
    { "german": "die Nichte (die Nichten)", "correct": "niece", "incorrect": ["nephew", "daughter", "aunt"] },
    { "german": "die Quelle (die Quellen)", "correct": "source", "incorrect": ["river", "lake", "pond"] },
    { "german": "bequem", "correct": "comfortable", "incorrect": ["uncomfortable", "hard", "uneasy"] },
    { "german": "ehrlich", "correct": "honest", "incorrect": ["dishonest", "deceitful", "sly"] },
    { "german": "bestätigen (bestätigt)", "correct": "confirm", "incorrect": ["deny", "assume", "question"] },
    { "german": "einatmen (eingeatmet)", "correct": "inhale", "incorrect": ["exhale", "cough", "sniff"] },
    { "german": "erhitzen (erhitzt)", "correct": "heat", "incorrect": ["freeze", "cool", "melt"] },
    { "german": "schätzen (geschätzt)", "correct": "estimate", "incorrect": ["calculate", "solve", "measure"] },
    { "german": "überqueren (überquert)", "correct": "cross", "incorrect": ["follow", "circumvent", "lead"] },
    { "german": "heftig", "correct": "violent", "incorrect": ["gentle", "mild", "calm"] },
    { "german": "klug", "correct": "wise", "incorrect": ["naive", "silly", "foolish"] },
    { "german": "leise", "correct": "quiet", "incorrect": ["loud", "noisy", "deafening"] },
    { "german": "scharf", "correct": "sharp", "incorrect": ["blunt", "smooth", "soft"] },
    { "german": "steil", "correct": "steep", "incorrect": ["flat", "level", "even"] },
    { "german": "das Gerücht (die Gerüchte)", "correct": "rumor", "incorrect": ["fact", "truth", "news"] },
    { "german": "vermeiden (vermieden)", "correct": "avoid", "incorrect": ["confront", "face", "encounter"] },
    { "german": "glänzend", "correct": "shiny", "incorrect": ["dull", "matte", "opaque"] },
    { "german": "die Stufe (die Stufen)", "correct": "step", "incorrect": ["door", "window", "wall"] },
    { "german": "schwingen (geschwungen)", "correct": "swing", "incorrect": ["jump", "slide", "roll"] },
    { "german": "feucht", "correct": "moist", "incorrect": ["dry", "hot", "cold"] },
    { "german": "der Strahl (die Strahlen)", "correct": "beam", "incorrect": ["shadow", "light", "glow"] },
    { "german": "die Falte (die Falten)", "correct": "wrinkle", "incorrect": ["spot", "stripe", "patch"] },
    { "german": "rasch", "correct": "quick", "incorrect": ["slow", "gradual", "steady"] },
    { "german": "die Wurzel (die Wurzeln)", "correct": "root", "incorrect": ["branch", "leaf", "stem"] },
    { "german": "knistern (geknistert)", "correct": "crackle", "incorrect": ["whistle", "hum", "buzz"] },
    { "german": "die Kluft (die Klüfte)", "correct": "gap", "incorrect": ["edge", "corner", "surface"] },
    { "german": "duftend", "correct": "fragrant", "incorrect": ["odorless", "stinky", "pungent"] },
    { "german": "der Funke (die Funken)", "correct": "spark", "incorrect": ["flame", "smoke", "ash"] },
    { "german": "das Geheimnis (die Geheimnisse)", "correct": "secret", "incorrect": ["mystery", "lie", "truth"] },
    { "german": "die Kette (die Ketten)", "correct": "chain", "incorrect": ["rope", "wire", "string"] },
    { "german": "das Lager (die Lager)", "correct": "camp", "incorrect": ["fort", "harbor", "base"] },
    { "german": "berühren (berührt)", "correct": "touch", "incorrect": ["hit", "push", "grab"] },
    { "german": "entscheiden (entschieden)", "correct": "decide", "incorrect": ["suggest", "think", "guess"] },
    { "german": "unterrichten (unterrichtet)", "correct": "teach", "incorrect": ["learn", "study", "practice"] },
    { "german": "vergleichen (verglichen)", "correct": "compare", "incorrect": ["contrast", "combine", "separate"] },
    { "german": "breit", "correct": "wide", "incorrect": ["narrow", "tall", "short"] },
    { "german": "flach", "correct": "flat", "incorrect": ["steep", "deep", "hilly"] },
    { "german": "hart", "correct": "hard", "incorrect": ["soft", "smooth", "gentle"] },
    { "german": "lebhaft", "correct": "lively", "incorrect": ["dull", "boring", "lifeless"] },
    { "german": "stolz", "correct": "proud", "incorrect": ["ashamed", "humble", "shy"] },
    { "german": "das Gleichgewicht (die Gleichgewichte)", "correct": "balance", "incorrect": ["contrast", "harmony", "symmetry"] },
    { "german": "verankern (verankert)", "correct": "anchor", "incorrect": ["float", "drift", "sail"] },
    { "german": "dicht", "correct": "dense", "incorrect": ["sparse", "thin", "light"] },
    { "german": "der Riss (die Risse)", "correct": "crack", "incorrect": ["hole", "dent", "scratch"] },
    { "german": "verbergen (verborgen)", "correct": "hide", "incorrect": ["show", "reveal", "expose"] },
    { "german": "klar", "correct": "clear", "incorrect": ["cloudy", "opaque", "blurry"] },
    { "german": "das Erbe (die Erben)", "correct": "heritage", "incorrect": ["debt", "gift", "burden"] },
    { "german": "schwingen (geschwungen)", "correct": "swing", "incorrect": ["slide", "rotate", "shake"] },
    { "german": "die Fähigkeit (die Fähigkeiten)", "correct": "ability", "incorrect": ["challenge", "task", "duty"] },
    { "german": "rasch", "correct": "quick", "incorrect": ["slow", "steady", "sluggish"] },
    { "german": "die Schicht (die Schichten)", "correct": "layer", "incorrect": ["corner", "angle", "edge"] },
    { "german": "fegen (gefegt)", "correct": "sweep", "incorrect": ["scrub", "mop", "wash"] },
    { "german": "die Hürde (die Hürden)", "correct": "hurdle", "incorrect": ["barrier", "fence", "wall"] },
    { "german": "bunt", "correct": "colorful", "incorrect": ["plain", "dull", "monochrome"] },
    { "german": "das Gerücht (die Gerüchte)", "correct": "rumor", "incorrect": ["fact", "news", "report"] },
    { "german": "ankündigen (angekündigt)", "correct": "announce", "incorrect": ["whisper", "argue", "mumble"] },
    { "german": "die Bewegung (die Bewegungen)", "correct": "movement", "incorrect": ["stillness", "silence", "pause"] },
    { "german": "zerbrechlich", "correct": "fragile", "incorrect": ["durable", "strong", "sturdy"] },
    { "german": "der Vorhang (die Vorhänge)", "correct": "curtain", "incorrect": ["rug", "blanket", "pillow"] },
    { "german": "fleißig", "correct": "diligent", "incorrect": ["lazy", "idle", "sluggish"] },
    { "german": "die Genehmigung (die Genehmigungen)", "correct": "permission", "incorrect": ["prohibition", "ban", "restriction"] },
    { "german": "erschöpft", "correct": "exhausted", "incorrect": ["energetic", "refreshed", "vigorous"] },
    { "german": "glühen (geglüht)", "correct": "glow", "incorrect": ["fade", "flash", "blink"] },
    { "german": "die Kluft (die Klüfte)", "correct": "chasm", "incorrect": ["peak", "plateau", "ridge"] },
    { "german": "nachdenken (nachgedacht)", "correct": "reflect", "incorrect": ["ignore", "disregard", "neglect"] },
    { "german": "die Pflicht (die Pflichten)", "correct": "duty", "incorrect": ["right", "freedom", "privilege"] },
    { "german": "rücksichtslos", "correct": "reckless", "incorrect": ["careful", "considerate", "cautious"] },
    { "german": "der Schatten (die Schatten)", "correct": "shadow", "incorrect": ["light", "glare", "brightness"] },
    { "german": "übertreiben (übertrieben)", "correct": "exaggerate", "incorrect": ["understate", "simplify", "minimize"] },
    { "german": "die Weisheit (die Weisheiten)", "correct": "wisdom", "incorrect": ["ignorance", "naivety", "inexperience"] },
    { "german": "begeistert", "correct": "excited", "incorrect": ["indifferent", "bored", "detached"] },
    { "german": "das Ereignis (die Ereignisse)", "correct": "event", "incorrect": ["routine", "habit", "custom"] },
    { "german": "hüpfen (gehüpft)", "correct": "hop", "incorrect": ["crawl", "slide", "wander"] },
    { "german": "die Ironie (die Ironien)", "correct": "irony", "incorrect": ["sincerity", "honesty", "frankness"] },
    { "german": "knirschen (geknirscht)", "correct": "grind", "incorrect": ["slide", "slip", "glide"] },
    { "german": "die Last (die Lasten)", "correct": "burden", "incorrect": ["relief", "ease", "comfort"] },
    { "german": "munter", "correct": "cheerful", "incorrect": ["gloomy", "morose", "sullen"] },
    { "german": "das Rätsel (die Rätsel)", "correct": "puzzle", "incorrect": ["solution", "answer", "clarity"] },
    { "german": "schütteln (geschüttelt)", "correct": "shake", "incorrect": ["hold", "lift", "carry"] },
    { "german": "die Tat (die Taten)", "correct": "deed", "incorrect": ["thought", "idea", "concept"] },
    { "german": "verzweifelt", "correct": "desperate", "incorrect": ["hopeful", "optimistic", "confident"] },
    { "german": "das Wagnis (die Wagnisse)", "correct": "venture", "incorrect": ["routine", "norm", "convention"] },
    { "german": "zögern (gezögert)", "correct": "hesitate", "incorrect": ["rush", "hurry", "accelerate"] },
    { "german": "die Anstrengung (die Anstrengungen)", "correct": "effort", "incorrect": ["ease", "leisure", "relaxation"] },
    { "german": "froh", "correct": "glad", "incorrect": ["sad", "upset", "disappointed"] },
    { "german": "die Droschke (die Droschken)", "correct": "cab", "incorrect": ["bus", "truck", "bicycle"] },
    { "german": "die Fessel (die Fesseln)", "correct": "shackle", "incorrect": ["rope", "chain", "wire"] },
    { "german": "der Anspruch (die Ansprüche)", "correct": "claim", "incorrect": ["denial", "offer", "plea"] },
    { "german": "erfinden (erfunden)", "correct": "invent", "incorrect": ["destroy", "follow", "copy"] },
    { "german": "aufmuntern (aufgemuntert)", "correct": "cheer up", "incorrect": ["discourage", "ignore", "depress"] },
    { "german": "die Weisung (die Weisungen)", "correct": "instruction", "incorrect": ["question", "answer", "explanation"] },
    { "german": "die Makulatur (die Makulaturen)", "correct": "waste paper", "incorrect": ["newspaper", "book", "magazine"] },
    { "german": "erledigen (erledigt)", "correct": "take care of", "incorrect": ["neglect", "overlook", "postpone"] },
    { "german": "knifflig", "correct": "tricky", "incorrect": ["simple", "straightforward", "easy"] },
    { "german": "langwierig", "correct": "tedious", "incorrect": ["exciting", "quick", "interesting"] },
    { "german": "voraussagen (vorausgesagt)", "correct": "predict", "incorrect": ["recall", "forget", "describe"] },
    { "german": "schlicht", "correct": "simple", "incorrect": ["complex", "decorated", "elaborate"] },
    { "german": "krass", "correct": "blatant", "incorrect": ["subtle", "minor", "insignificant"] },
    { "german": "zerknüllen (zerknüllt)", "correct": "crumple", "incorrect": ["flatten", "smooth", "unfold"] },
    { "german": "grob", "correct": "rough", "incorrect": ["smooth", "soft", "gentle"] },
    { "german": "abschaben (abgeschabt)", "correct": "scrape off", "incorrect": ["paint on", "glue on", "apply"] },
    { "german": "aufspüren (aufgespürt)", "correct": "track down", "incorrect": ["lose", "ignore", "misplace"] },
    { "german": "abhaken (abgehakt)", "correct": "check off", "incorrect": ["add", "attach", "tie"] },
    { "german": "tilgen (getilgt)", "correct": "erase", "incorrect": ["record", "write", "draw"] },
    { "german": "anhören (angehört)", "correct": "listen to", "incorrect": ["speak", "ignore", "mutter"] },
    { "german": "ausgiebig", "correct": "extensive", "incorrect": ["limited", "brief", "insignificant"] },
    { "german": "eigen", "correct": "own", "incorrect": ["borrowed", "public", "common"] },
    { "german": "treffen (getroffen)", "correct": "meet", "incorrect": ["miss", "depart", "avoid"] },
    { "german": "vergießen (vergossen)", "correct": "shed", "incorrect": ["collect", "retain", "absorb"] },
    { "german": "widmen (gewidmet)", "correct": "dedicate", "incorrect": ["neglect", "ignore", "condemn"] },
    { "german": "der Entwurf (die Entwürfe)", "correct": "draft", "incorrect": ["final", "completion", "execution"] },
    { "german": "der Matrose (die Matrosen)", "correct": "sailor", "incorrect": ["pilot", "captain", "soldier"] },
    { "german": "das Verdienst (die Verdienste)", "correct": "merit", "incorrect": ["fault", "deficit", "demerit"] },
    { "german": "herausgeben (herausgegeben)", "correct": "issue", "incorrect": ["withdraw", "retract", "conceal"] },
    { "german": "verweisen (verwiesen)", "correct": "refer", "incorrect": ["confuse", "contradict", "solve"] },
    { "german": "abweichen (abgewichen)", "correct": "deviate", "incorrect": ["conform", "align", "agree"] },
    { "german": "nachahmen (nachgeahmt)", "correct": "imitate", "incorrect": ["originate", "innovate", "pioneer"] },
    { "german": "der Stil (die Stile)", "correct": "style", "incorrect": ["disorder", "chaos", "mess"] },
    { "german": "die Trommel (die Trommeln)", "correct": "drum", "incorrect": ["flute", "violin", "trumpet"] },
    { "german": "aufweisen (aufgewiesen)", "correct": "exhibit", "incorrect": ["conceal", "hide", "remove"] },
    { "german": "die Depesche (die Depeschen)", "correct": "dispatch", "incorrect": ["package", "letter", "card"] },
    { "german": "der Düsenjäger (die Düsenjäger)", "correct": "jet fighter", "incorrect": ["tank", "submarine", "battleship"] },
    { "german": "erwägen (erwogen)", "correct": "contemplate", "incorrect": ["ignore", "decide", "act"] },
    { "german": "verleihen (verliehen)", "correct": "lend", "incorrect": ["borrow", "keep", "buy"] },
    { "german": "vorrücken (vorgerrückt)", "correct": "advance", "incorrect": ["retreat", "stagnate", "surrender"] },
    { "german": "das Gedränge", "correct": "hustle", "incorrect": ["calm", "order", "silence"] },
    { "german": "betäuben (betäubt)", "correct": "numb", "incorrect": ["sharpen", "agitate", "excite"] },
    { "german": "wogen (gewogt)", "correct": "surge", "incorrect": ["abate", "still", "freeze"] },
    { "german": "der Eintopf (die Eintöpfe)", "correct": "stew", "incorrect": ["soup", "salad", "roast"] },
    { "german": "der Napf (die Näpfe)", "correct": "bowl", "incorrect": ["plate", "cup", "tray"] },
    { "german": "schwammig", "correct": "spongy", "incorrect": ["rigid", "hard", "solid"] },
    { "german": "würgen (gewürgt)", "correct": "choke", "incorrect": ["breathe", "inhale", "exhale"] },
    { "german": "der Matsch", "correct": "mud", "incorrect": ["sand", "gravel", "dust"] },
    { "german": "die Ente (die Enten)", "correct": "duck", "incorrect": ["chicken", "goose", "turkey"] },
    { "german": "die Auflage (die Auflagen)", "correct": "edition", "incorrect": ["manuscript", "draft", "sketch"] },
    { "german": "beleben (belebt)", "correct": "revitalize", "incorrect": ["deactivate", "destroy", "suppress"] },
    { "german": "der Schwanz (die Schwänze)", "correct": "tail", "incorrect": ["head", "paw", "mane"] },
    { "german": "die Gabel (die Gabeln)", "correct": "fork", "incorrect": ["knife", "plate", "cup"] },
    { "german": "der Tisch (die Tische)", "correct": "table", "incorrect": ["door", "window", "bed"] },
    { "german": "der Stuhl (die Stühle)", "correct": "chair", "incorrect": ["sofa", "lamp", "desk"] },
    { "german": "das Wasser (die Wasser)", "correct": "water", "incorrect": ["juice", "milk", "coffee"] },
    { "german": "das Brot (die Brote)", "correct": "bread", "incorrect": ["cheese", "butter", "eggs"] },
    { "german": "die Milch (die Milch)", "correct": "milk", "incorrect": ["water", "juice", "soda"] },
    { "german": "der Apfel (die Äpfel)", "correct": "apple", "incorrect": ["orange", "banana", "grape"] },
    { "german": "die Banane (die Bananen)", "correct": "banana", "incorrect": ["apple", "pear", "strawberry"] },
    { "german": "die Orange (die Orangen)", "correct": "orange", "incorrect": ["grapefruit", "lemon", "lime"] },
    { "german": "die Traube (die Trauben)", "correct": "grape", "incorrect": ["cherry", "strawberry", "raspberry"] },
    { "german": "das Gemüse (das Gemüse)", "correct": "vegetables", "incorrect": ["fruit", "meat", "bread"] },
    { "german": "das Fleisch (das Fleisch)", "correct": "meat", "incorrect": ["fish", "chicken", "eggs"] },
    { "german": "der Fisch (die Fische)", "correct": "fish", "incorrect": ["shrimp", "crab", "lobster"] },
    { "german": "das Huhn (die Hühner)", "correct": "chicken", "incorrect": ["turkey", "duck", "goose"] },
    { "german": "das Ei (die Eier)", "correct": "egg", "incorrect": ["milk", "butter", "cheese"] },
    { "german": "der Käse (die Käse)", "correct": "cheese", "incorrect": ["yogurt", "milk", "butter"] },
    { "german": "das Buch (die Bücher)", "correct": "book", "incorrect": ["pen", "paper", "pencil"] },
    { "german": "der Stift (die Stifte)", "correct": "pen", "incorrect": ["pencil", "eraser", "ruler"] },
    { "german": "das Papier (die Papiere)", "correct": "paper", "incorrect": ["book", "notebook", "pencil"] },
    { "german": "der Bleistift (die Bleistifte)", "correct": "pencil", "incorrect": ["pen", "crayon", "marker"] },
    { "german": "der Teller (die Teller)", "correct": "plate", "incorrect": ["bowl", "cup", "spoon"] },
    { "german": "die Tasse (die Tassen)", "correct": "cup", "incorrect": ["mug", "glass", "bowl"] },
    { "german": "das Messer (die Messer)", "correct": "knife", "incorrect": ["spoon", "fork", "scissors"] },
    { "german": "der Löffel (die Löffel)", "correct": "spoon", "incorrect": ["fork", "knife", "cup"] },
    { "german": "die Gabel (die Gabeln)", "correct": "fork", "incorrect": ["knife", "spoon", "plate"] },
    { "german": "der Löffel (die Löffel)", "correct": "spoon", "incorrect": ["fork", "knife", "plate"] },
    { "german": "der Stuhl (die Stühle)", "correct": "chair", "incorrect": ["sofa", "bed", "table"] },
    { "german": "das Bett (die Betten)", "correct": "bed", "incorrect": ["sofa", "chair", "table"] },
    { "german": "das Sofa (die Sofas)", "correct": "sofa", "incorrect": ["chair", "bed", "table"] },
    { "german": "der Schrank (die Schränke)", "correct": "closet", "incorrect": ["dresser", "drawer", "shelf"] },
    { "german": "die Kommode (die Kommoden)", "correct": "dresser", "incorrect": ["closet", "shelf", "nightstand"] },
    { "german": "die Schublade (die Schubladen)", "correct": "drawer", "incorrect": ["shelf", "closet", "dresser"] },
    { "german": "das Regal (die Regale)", "correct": "shelf", "incorrect": ["drawer", "closet", "dresser"] },
    { "german": "die Lampe (die Lampen)", "correct": "lamp", "incorrect": ["light", "bulb", "chandelier"] },
    { "german": "das Licht (die Lichter)", "correct": "light", "incorrect": ["lamp", "bulb", "chandelier"] },
    { "german": "die Glühbirne (die Glühbirnen)", "correct": "bulb", "incorrect": ["lamp", "light", "chandelier"] },
    { "german": "der Kronleuchter (die Kronleuchter)", "correct": "chandelier", "incorrect": ["lamp", "light", "bulb"] },
    { "german": "der Teppich (die Teppiche)", "correct": "rug", "incorrect": ["carpet", "floor", "mat"] },
    { "german": "der Vorhang (die Vorhänge)", "correct": "curtain", "incorrect": ["blind", "drape", "shade"] },
    { "german": "das Fenster (die Fenster)", "correct": "window", "incorrect": ["door", "wall", "ceiling"] },
    { "german": "die Tür (die Türen)", "correct": "door", "incorrect": ["window", "wall", "floor"] },
    { "german": "die Wand (die Wände)", "correct": "wall", "incorrect": ["ceiling", "floor", "door"] },
    { "german": "die Decke (die Decken)", "correct": "ceiling", "incorrect": ["wall", "floor", "roof"] },
    { "german": "der Boden (die Böden)", "correct": "floor", "incorrect": ["wall", "ceiling", "carpet"] },
    { "german": "das Haus (die Häuser)", "correct": "house", "incorrect": ["apartment", "building", "office"] },
    { "german": "die Wohnung (die Wohnungen)", "correct": "apartment", "incorrect": ["house", "building", "room"] },
    { "german": "das Gebäude (die Gebäude)", "correct": "building", "incorrect": ["house", "apartment", "office"] },
    { "german": "das Büro (die Büros)", "correct": "office", "incorrect": ["building", "apartment", "room"] },
    { "german": "das Zimmer (die Zimmer)", "correct": "room", "incorrect": ["office", "apartment", "building"] },
    { "german": "das Bad (die Bäder)", "correct": "bathroom", "incorrect": ["kitchen", "bedroom", "living room"] },
    { "german": "die Küche (die Küchen)", "correct": "kitchen", "incorrect": ["bathroom", "bedroom", "living room"] },
    { "german": "das Schlafzimmer (die Schlafzimmer)", "correct": "bedroom", "incorrect": ["bathroom", "kitchen", "living room"] },
    { "german": "das Wohnzimmer (die Wohnzimmer)", "correct": "living room", "incorrect": ["bathroom", "kitchen", "bedroom"] },
    { "german": "das Bett (die Betten)", "correct": "bed", "incorrect": ["sofa", "chair", "table"] },
    { "german": "der Spiegel (die Spiegel)", "correct": "mirror", "incorrect": ["picture", "frame", "painting"] },
    { "german": "das Bild (die Bilder)", "correct": "picture", "incorrect": ["mirror", "frame", "painting"] },
    { "german": "der Rahmen (die Rahmen)", "correct": "frame", "incorrect": ["mirror", "picture", "painting"] },
    { "german": "das Gemälde (die Gemälde)", "correct": "painting", "incorrect": ["mirror", "picture", "frame"] },
    { "german": "die Uhr (die Uhren)", "correct": "clock", "incorrect": ["watch", "timer", "alarm"] },
    { "german": "die Armbanduhr (die Armbanduhren)", "correct": "watch", "incorrect": ["clock", "timer", "alarm"] },
    { "german": "der Wecker (die Wecker)", "correct": "alarm", "incorrect": ["clock", "watch", "timer"] },
    { "german": "der Timer (die Timer)", "correct": "timer", "incorrect": ["clock", "watch", "alarm"] },
    { "german": "der Fernseher (die Fernseher)", "correct": "television", "incorrect": ["computer", "radio", "phone"] },
    { "german": "der Computer (die Computer)", "correct": "computer", "incorrect": ["television", "radio", "phone"] },
    { "german": "das Radio (die Radios)", "correct": "radio", "incorrect": ["television", "computer", "phone"] },
    { "german": "das Telefon (die Telefone)", "correct": "phone", "incorrect": ["television", "computer", "radio"] },
    { "german": "das Sofa (die Sofas)", "correct": "sofa", "incorrect": ["chair", "bed", "table"] },
    { "german": "der Sessel (die Sessel)", "correct": "armchair", "incorrect": ["sofa", "chair", "bed"] },
    { "german": "der Hocker (die Hocker)", "correct": "stool", "incorrect": ["chair", "sofa", "armchair"] },
    { "german": "der Teppich (die Teppiche)", "correct": "rug", "incorrect": ["carpet", "floor", "mat"] },
    { "german": "der Teppichboden (die Teppichböden)", "correct": "carpet", "incorrect": ["rug", "floor", "mat"] },
    { "german": "die Fußmatte (die Fußmatten)", "correct": "doormat", "incorrect": ["rug", "carpet", "floor"] },
    { "german": "der Schrank (die Schränke)", "correct": "closet", "incorrect": ["dresser", "drawer", "shelf"] },
    { "german": "die Aussage (die Aussagen)", "correct": "statement", "incorrect": ["question", "command", "silence"] },
    { "german": "beleben (belebt)", "correct": "animate", "incorrect": ["deter", "dispirit", "discourage"] },
    { "german": "der Schwanz (die Schwänze)", "correct": "tail", "incorrect": ["head", "wing", "beak"] },
    { "german": "vorweisen (vorgewiesen)", "correct": "demonstrate", "incorrect": ["conceal", "lose", "discard"] },
    { "german": "das Getriebe (die Getriebe)", "correct": "gearbox", "incorrect": ["engine", "brake", "wheel"] },
    { "german": "herausgeben (herausgegeben)", "correct": "publish", "incorrect": ["conceal", "destroy", "collect"] },
    { "german": "verweisen (verwiesen)", "correct": "expel", "incorrect": ["admit", "welcome", "invite"] },
    { "german": "abweichen (abgewichen)", "correct": "differ", "incorrect": ["match", "mirror", "echo"] },
    { "german": "nachahmen (nachgeahmt)", "correct": "mimic", "incorrect": ["originate", "innovate", "neglect"] },
    { "german": "der Stil (die Stile)", "correct": "style", "incorrect": ["disorder", "clumsiness", "rudeness"] },
    { "german": "die Trommel (die Trommeln)", "correct": "drum", "incorrect": ["horn", "bell", "whistle"] },
    { "german": "aufweisen (aufgewiesen)", "correct": "show", "incorrect": ["hide", "cover", "blind"] },
    { "german": "die Depesche (die Depeschen)", "correct": "dispatch", "incorrect": ["arrival", "dispatch", "departure"] },
    { "german": "der Düsenjäger (die Düsenjäger)", "correct": "jet fighter", "incorrect": ["tank", "ship", "submarine"] },
    { "german": "erwägen (erwogen)", "correct": "consider", "incorrect": ["discard", "execute", "initiate"] },
    { "german": "verleihen (verliehen)", "correct": "award", "incorrect": ["revoke", "withdraw", "hold"] },
    { "german": "vorrücken (vorgerrückt)", "correct": "proceed", "incorrect": ["retreat", "rest", "halt"] },
    { "german": "das Gedränge", "correct": "crowd", "incorrect": ["loneliness", "openness", "emptiness"] },
    { "german": "betäuben (betäubt)", "correct": "stun", "incorrect": ["enlighten", "clarify", "awaken"] },
    { "german": "wogen (gewogt)", "correct": "billow", "incorrect": ["dry", "smooth", "straighten"] },
    { "german": "der Eintopf (die Eintöpfe)", "correct": "stew", "incorrect": ["grill", "bake", "fry"] },
    { "german": "der Napf (die Näpfe)", "correct": "bowl", "incorrect": ["plate", "jar", "pan"] },
    { "german": "schwammig", "correct": "mushy", "incorrect": ["firm", "hard", "rigid"] },
    { "german": "würgen (gewürgt)", "correct": "strangle", "incorrect": ["caress", "release", "free"] },
    { "german": "der Matsch", "correct": "slush", "incorrect": ["dust", "sand", "gravel"] },
    { "german": "die Ente (die Enten)", "correct": "duck", "incorrect": ["swan", "goose", "eagle"] },
    { "german": "die Auflage (die Auflagen)", "correct": "circulation", "incorrect": ["edition", "publication", "release"] },
    { "german": "beleben (belebt)", "correct": "revive", "incorrect": ["suppress", "inhibit", "quell"] },
    { "german": "der Schwanz (die Schwänze)", "correct": "tail", "incorrect": ["fin", "wing", "hoof"] },
    { "german": "prägen (geprägt)", "correct": "shape", "incorrect": ["mold", "frame", "construct"] },
    { "german": "das Bindeglied (die Bindeglieder)", "correct": "connecting link", "incorrect": ["joint", "tie", "bond"] },
    { "german": "die Garnele (die Garnelen)", "correct": "shrimp", "incorrect": ["crab", "lobster", "clam"] },
    { "german": "borstig", "correct": "bristly", "incorrect": ["smooth", "slick", "glossy"] },
    { "german": "behende", "correct": "nimble", "incorrect": ["clumsy", "awkward", "slow"] },
    { "german": "die Gasse (die Gassen)", "correct": "alley", "incorrect": ["road", "avenue", "boulevard"] },
    { "german": "bergab", "correct": "downhill", "incorrect": ["uphill", "level", "flat"] },
    { "german": "der Gipsabguß (die Gipsabgüsse)", "correct": "plaster cast", "incorrect": ["sculpture", "mold", "carving"] },
    { "german": "schären (geschärt)", "correct": "swarm", "incorrect": ["group", "pack", "herd"] },
    { "german": "scharen (gescharrt)", "correct": "flock", "incorrect": ["group", "pack", "herd"] },
    { "german": "die Trümmer", "correct": "debris", "incorrect": ["rubble", "remains", "residue"] },
    { "german": "der Mörtel (die Mörtel)", "correct": "mortar", "incorrect": ["cement", "glue", "paste"] },
    { "german": "übersät", "correct": "littered", "incorrect": ["covered", "filled", "paved"] },
    { "german": "prasseln (geprasselt)", "correct": "patter", "incorrect": ["pour", "drip", "splash"] },
    { "german": "wölben (gewölbt)", "correct": "arch", "incorrect": ["bend", "curve", "straighten"] },
    { "german": "versteifen (versteift)", "correct": "stiffen", "incorrect": ["soften", "loosen", "relax"] },
    { "german": "der Argwohn", "correct": "suspicion", "incorrect": ["trust", "confidence", "certainty"] },
    { "german": "feindselig", "correct": "hostile", "incorrect": ["friendly", "welcoming", "amiable"] },
    { "german": "verschränken (verschränkt)", "correct": "entangle", "incorrect": ["separate", "align", "order"] },
    { "german": "der Backstein (die Backsteine)", "correct": "brick", "incorrect": ["block", "stone", "slab"] },
    { "german": "barfüßig", "correct": "barefoot", "incorrect": ["shod", "booted", "sneakered"] },
    { "german": "schlürfen (geschlürft)", "correct": "sip", "incorrect": ["gulp", "swig", "quaff"] },
    { "german": "schlurfen (geschlurft)", "correct": "shuffle", "incorrect": ["march", "jog", "sprint"] },
    { "german": "toben (getobt)", "correct": "rage", "incorrect": ["calm", "soothe", "appease"] },
    { "german": "sich austoben (ausgetobt)", "correct": "let off steam", "incorrect": ["restrain", "suppress", "conserve"] },
    { "german": "aufgedunsen", "correct": "bloated", "incorrect": ["shriveled", "deflated", "compressed"] },
    { "german": "watscheln (gewatschelt)", "correct": "waddle", "incorrect": ["stride", "trot", "dash"] },
    { "german": "nachstellen (nachgestellt)", "correct": "recreate", "incorrect": ["destroy", "dismantle", "erase"] },
    { "german": "grell", "correct": "glaring", "incorrect": ["dim", "subdued", "faint"] },
    { "german": "abzweigen (abgezweigt)", "correct": "branch off", "incorrect": ["merge", "unite", "converge"] },
    { "german": "versäumen (versäumt)", "correct": "miss", "incorrect": ["attend", "catch", "participate"] },
    { "german": "die Unbesonnenheit", "correct": "imprudence", "incorrect": ["wisdom", "prudence", "caution"] },
    { "german": "verführen (verführt)", "correct": "seduce", "incorrect": ["repulse", "disgust", "turn off"] },
    { "german": "nebelhaft", "correct": "misty", "incorrect": ["clear", "sunny", "bright"] },
    { "german": "die Pfütze (die Pfützen)", "correct": "puddle", "incorrect": ["lake", "pond", "river"] },
    { "german": "verrücken (verrückt)", "correct": "shift", "incorrect": ["stabilize", "fix", "secure"] },
    { "german": "verzeihen (verziehen)", "correct": "pardon", "incorrect": ["blame", "accuse", "condemn"] },
    { "german": "versöhnen (versöhnt)", "correct": "reconcile", "incorrect": ["separate", "divide", "conflict"] },
    { "german": "unmittelbar", "correct": "immediate", "incorrect": ["delayed", "indirect", "gradual"] },
    { "german": "vertraulich", "correct": "confidential", "incorrect": ["public", "known", "obvious"] },
    { "german": "einst", "correct": "once", "incorrect": ["often", "seldom", "frequently"] },
    { "german": "die Nachlässigkeit", "correct": "carelessness", "incorrect": ["caution", "carefulness", "prudence"] },
    { "german": "überwinden (überwunden)", "correct": "overcome", "incorrect": ["surrender", "fail", "yield"] },
    { "german": "der Rollladen (die Rollläden)", "correct": "shutters", "incorrect": ["windows", "doors", "curtains"] },
    { "german": "die Sanierung", "correct": "renovation", "incorrect": ["destruction", "damage", "decay"] },
    { "german": "die Glühbirne (die Glühbirnen)", "correct": "lightbulb", "incorrect": ["lantern", "lamp", "flashlight"] },
    { "german": "wiederum", "correct": "in turn", "incorrect": ["together", "simultaneously", "at once"] },
    { "german": "geglückt", "correct": "succeeded", "incorrect": ["failed", "lost", "ruined"] },
    { "german": "aufwendig", "correct": "elaborate", "incorrect": ["simple", "easy", "basic"] },
    { "german": "der Anlass (die Anlässe)", "correct": "reason", "incorrect": ["effect", "result", "outcome"] },
    { "german": "der Grenzwert (die Grenzwerte)", "correct": "limit", "incorrect": ["excess", "infinity", "boundlessness"] },
    { "german": "die Anleihe (die Anleihen)", "correct": "bonds", "incorrect": ["stocks", "shares", "equities"] },
    { "german": "aufschlussreich", "correct": "insightful", "incorrect": ["misleading", "confusing", "unclear"] },
    { "german": "gleichgültig", "correct": "indifferent", "incorrect": ["concerned", "interested", "invested"] },
    { "german": "dasselbe Ding", "correct": "same thing", "incorrect": ["different thing", "opposite", "contrast"] },
    { "german": "die Fachanhänge (die Fachanhängen)", "correct": "technical appendices", "incorrect": ["main text", "preface", "introduction"] },
    { "german": "der Adlige (die Adligen)", "correct": "nobleman", "incorrect": ["peasant", "commoner", "servant"] },
    { "german": "verlegen", "correct": "embarrassed", "incorrect": ["proud", "confident", "pleased"] },
    { "german": "das Ufer (die Ufer)", "correct": "riverbank", "incorrect": ["sea", "ocean", "lake"] },
    { "german": "würdevoll", "correct": "dignified", "incorrect": ["shameful", "disgraceful", "undignified"] },
    { "german": "eigenartig", "correct": "peculiar", "incorrect": ["normal", "usual", "common"] },
    { "german": "das Rudel (die Rudel)", "correct": "pack", "incorrect": ["flock", "herd", "swarm"] },
    { "german": "abgeschafft", "correct": "abolished", "incorrect": ["established", "created", "founded"] },
    { "german": "der Abgrund (die Abgründe)", "correct": "abyss", "incorrect": ["peak", "hilltop", "summit"] },
    { "german": "annehmen (angenommen)", "correct": "accept", "incorrect": ["refuse", "decline", "reject"] },
    { "german": "aufholen (aufgeholt)", "correct": "catch up", "incorrect": ["fall behind", "stop", "pause"] },
    { "german": "anrichten (angerichtet)", "correct": "dish", "incorrect": ["consume", "eat", "bite"] },
    { "german": "der Segen (die Segen)", "correct": "blessing", "incorrect": ["curse", "disaster", "nuisance"] },
    { "german": "leugnen (geleugnet)", "correct": "deny", "incorrect": ["admit", "acknowledge", "confirm"] },
    { "german": "eintreffen (eingetroffen)", "correct": "arrive", "incorrect": ["depart", "leave", "exit"] },
    { "german": "sich aneignen (sich angeeignet)", "correct": "appropriate", "incorrect": ["reject", "discard", "ignore"] },
    { "german": "anheuern (angeheuert)", "correct": "hire", "incorrect": ["fire", "dismiss", "reject"] },
    { "german": "bestärken (bestärkt)", "correct": "encourage", "incorrect": ["discourage", "dissuade", "deter"] },
    { "german": "sich anschnallen (sich angeschnallt)", "correct": "buckle up", "incorrect": ["unfasten", "loosen", "detach"] },
    { "german": "die Eingeweide", "correct": "guts", "incorrect": ["skin", "bones", "muscles"] },
    { "german": "säumen (gesäumt)", "correct": "hem", "incorrect": ["stretch", "shorten", "lengthen"] },
    { "german": "stöbern (gestöbert)", "correct": "rummage", "incorrect": ["organize", "arrange", "tidy"] },
    { "german": "gestatten (gestattet)", "correct": "allow", "incorrect": ["forbid", "prohibit", "deny"] },
    { "german": "kneifen (gekniffen)", "correct": "pinch", "incorrect": ["push", "pull", "hit"] },
    { "german": "fauchen (gefaucht)", "correct": "hiss", "incorrect": ["whisper", "shout", "yell"] },
    { "german": "bügeln (gebügelt)", "correct": "iron", "incorrect": ["fold", "wash", "dry"] },
    { "german": "sich anbiedern (sich angebiedert)", "correct": "ingratiate", "incorrect": ["alienate", "offend", "repulse"] },
    { "german": "wimmeln (gewimmelt)", "correct": "teeming", "incorrect": ["empty", "vacant", "desolate"] },
    { "german": "aufteilen (aufgeteilt)", "correct": "split up", "incorrect": ["unite", "join", "merge"] },
    { "german": "die Beilegung (die Beilegungen)", "correct": "settlement", "incorrect": ["conflict", "dispute", "confrontation"] },
    { "german": "aufpassen (aufgepasst)", "correct": "watch after", "incorrect": ["ignore", "neglect", "overlook"] },
    { "german": "die Hetze (die Hetzen)", "correct": "rush", "incorrect": ["run", "hurry", "dash"] }
]
"""

# Convert the string to a Python list of dictionaries
word_pairs = json.loads(word_pairs_js)

# Add each word pair to the database
def add_word_pairs_to_db(word_pairs):
    for pair in word_pairs:
        existing_word = WordPair.query.filter_by(german=pair['german']).first()
        if not existing_word:
            print(f"Adding word {pair['german']}")
            new_word = WordPair(
                german=pair["german"],
                correct=pair["correct"],
                incorrect1=pair["incorrect"][0],
                incorrect2=pair["incorrect"][1],
                incorrect3=pair["incorrect"][2],
            )
            db.session.add(new_word)
    db.session.commit()

if __name__ == '__main__':
    with app.app_context():
        print("Creating database...")
        db.create_all()  # Create database tables
        add_word_pairs_to_db(word_pairs)  # Populate the database
